defaults:
  - dataset: shhs1
  - model: random_forest
  - features: bmi
  - target: ahi_a0h3a
hydra:
  sweep:
    dir: results
    subdir: initial_study/${now:%Y-%m-%d}/${now:%H-%M}/${hydra.job.override_dirname}